name: ci-cpu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jobname: [JACC-threads]

    steps:
      - name: Checkout Action
        uses: actions/checkout@v4

      - name: Instantiate
        run: julia --project -e 'using Pkg; Pkg.instantiate();'

      - name: Test Threads
        run: julia -t 4 --project -e 'using Pkg; Pkg.test()'

  macos:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        jobname: [JACC-threads]

    steps:
      - name: Checkout Action
        uses: actions/checkout@v4

      - name: Instantiate
        run: julia --project -e 'using Pkg; Pkg.instantiate();'

      - name: Test Threads
        run: julia -t 3 --project -e 'using Pkg; Pkg.test()'
